version: "3.8"

services:
  backend:
    image: yashs3324/edviron-backend:latest
    container_name: edviron-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PG_KEY=edvtest01
      - PG_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVlSWQiOiI2NWIwZTU1MmRkMzE5NTBhOWI0MWM1YmEiLCJJbmRleE9mQXBpS2V5Ijo2LCJpYXQiOjE3MTE2MjIyNzAsImV4cCI6MTc0MzE3OTg3MH0.Rye77Dp59GGxwCmwWekJHRj6edXWJnff9finjMhxKuw
      - SCHOOL_ID=65b0e6293e9f76a9694d84b4
      - MONGODB_URI=mongodb+srv://yash:12345678%40123@cluster0.tnfs0tz.mongodb.net/mydb?retryWrites=true&w=majority
      - JWT_SECRET=dfgdhfgjkgfds
      - PORT=4000
      - CLIENT_URL=https://edviron.yashprojects.online
      - FRONTEND_URL=https://edviron.yashprojects.online
    restart: unless-stopped
    networks:
      - edviron-network

  frontend:
    image: yashs3324/edviron-frontend:latest
    container_name: edviron-frontend
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://edbe.yashprojects.online
      - NEXT_PUBLIC_PG_API_URL=https://dev-vanilla.edviron.com/erp
      - NEXT_PUBLIC_PG_KEY=edvtest01
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - edviron-network

networks:
  edviron-network:
    driver: bridge
